---
title: "Object Transport Analysis"
author: "Shanaa Modchalingam"
date: '2023'
output: 
  html_notebook:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    
---

```{r setup, include=FALSE, warning=FALSE}
rm(list = ls()) # clean environment

source("../src/helper_funcs.R")
library(data.table)
library(tidyverse)
library(future) # for parallel processing
library(collections)
library(ggbeeswarm)

# Helper functions
##### Helper functions #####
slope <- function(x, y) {
  return(cov(x, y) / var(x))
}

intercept <- function(x, y, slope) {
  b <- mean(y) - (slope * mean(x))
  return(b)
}
```

## Data Import and Summaries
```{r}
# import data
data_path <- "../data/preprocessed/omnibus/omnibus_bl_corrected.csv"

all_data <- fread(data_path)

## Setup ##
palette <- dict(
  list(
    "cube" = "#6aafd2",
    "sphere" = "#f07c04"
  )
)
# make any and all summary dfs here
by_trial_df <- all_data %>%
  group_by(exp, type, trial_num) %>%
  summarise(
    mean_obj_angle_3cm_move = mean(obj_angle_3cm_move),
    ci_obj_angle_3cm_move = vector_confint(obj_angle_3cm_move),
    mean_obj_time_start_move = mean(obj_time_start_move),
    ci_obj_time_start_move = vector_confint(obj_time_start_move),
    mean_obj_time_reach = mean(obj_time_reach),
    ci_obj_time_reach = vector_confint(obj_time_reach),
    mean_obj_time_total_move = mean(obj_time_total_move),
    ci_obj_time_total_move = vector_confint(obj_time_total_move),
    mean_hand_angle_3cm_move = mean(hand_angle_3cm_move),
    ci_hand_angle_3cm_move = vector_confint(hand_angle_3cm_move),
    mean_hand_time_start_move = mean(hand_time_start_move),
    ci_hand_time_start_move = vector_confint(hand_time_start_move),
    mean_hand_time_reach = mean(hand_time_reach),
    ci_hand_time_reach = vector_confint(hand_time_reach),
    mean_hand_time_total_move = mean(hand_time_total_move),
    ci_hand_time_total_move = vector_confint(hand_time_total_move),
  )


## Isolate experiments and summarize ##
sr_30_all <- all_data %>%
  filter(exp == "sr_30") %>%
  mutate(unsigned_angle = obj_angle_3cm_move * obj_shape_sign * -1)

sr_30_ppt_training <- sr_30_all %>%
  filter(block_num == 16) %>%
  mutate(trial_set = case_when(
    trial_num <= 141 ~ 1,
    trial_num >= 316 ~ 2,
    TRUE ~ 100
  ))

sr_30_clamped <- sr_30_all %>%
  filter(block_num > 16, type == "clamped") %>%
  mutate(trained_obj_factor = case_when(
    trainedfirst_obj_shape == obj_shape ~ "trained_obj",
    TRUE ~ "untrained_obj"
  )) %>%
  mutate(trained_hand_factor = case_when(
    hand == "r" ~ "trained_hand",
    TRUE ~ "untrained_hand"
  )) %>%
  mutate(trained_obj_hand_factor = paste0(trained_obj_factor, "_", trained_hand_factor))
```
# S30 Training per-trial plot
```{r}
sr_30_exp_training <- sr_30_ppt_training %>%
  group_by(trial_num) %>% # note: only one where don't need to group_by ppid
  summarise(
    mean_unsigned_angle = mean(unsigned_angle),
    ci_unsigned_angle = vector_confint(unsigned_angle)
  )

data <- sr_30_exp_training

# set up plot
p <- data %>%
  ggplot(
    aes(
      x = trial_num - 138, y = mean_unsigned_angle
    )
  ) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(
    x = "Trial Number",
    y = "Angular Error (°)"
  )

# add horizontal lines
p <- p +
  geom_hline(
    yintercept = c(0, 30), linewidth = 0.4,
    colour = "#CCCCCC", linetype = "solid"
  ) +
  geom_hline(
    yintercept = c(15), linewidth = 0.4,
    colour = "#CCCCCC", linetype = "dashed"
  )

# add a grey box behind trial sets
p <- p +
  geom_rect(
    xmin = 1, xmax = 3,
    ymin = -5, ymax = 30,
    colour = "#CCCCCC", fill = "#CCCCCC"
  ) +
  geom_rect(
    xmin = 178, xmax = 180,
    ymin = -5, ymax = 30,
    colour = "#CCCCCC", fill = "#CCCCCC"
  )

p <- p +
  scale_y_continuous(
    limits = c(-15, 40),
    breaks = c(0, 15, 30),
    labels = c(0, 15, 30)
  ) +
  scale_x_continuous(
    limits = c(0, 180),
    breaks = c(0, 60, 120, 180),
    labels = c(0, 60, 120, 180)
  )

# set font size to 11
p <- p +
  theme(text = element_text(size = 11))

# add confidence intervals
p <- p + geom_ribbon(
  aes(
    ymin = mean_unsigned_angle - ci_unsigned_angle,
    ymax = mean_unsigned_angle + ci_unsigned_angle
  ),
  fill = "#6aafd2", colour = NA, alpha = 0.3
)

# add data
p <- p + geom_line(colour = "#6aafd2")


# save
ggsave(
  p,
  filename = "../plots/paper_figs/sr_30_training.pdf", device = "pdf",
  height = 4, width = 6
)

p
```
# S30 Training trial set plot
```{r}
sr_30_ppt_trial_sets <- sr_30_ppt_training %>%
  filter(trial_set < 5) %>%
  group_by(ppid, trial_set) %>%
  summarise(
    mean_trial_set_angle = mean(unsigned_angle)
  )

sr_30_ppt_trial_sets$trial_set <- as.factor(sr_30_ppt_trial_sets$trial_set)

sr_30_trial_set_devs <- sr_30_ppt_trial_sets %>%
  group_by(trial_set) %>%
  summarise(
    trial_set_mean = mean(mean_trial_set_angle),
    trial_set_ci = vector_confint(mean_trial_set_angle)
  )

data_ppt <- sr_30_ppt_trial_sets
data_trial_set <- sr_30_trial_set_devs

# set up plot
p <- data_trial_set %>%
  ggplot(
    aes(
      x = trial_set, y = trial_set_mean,
      color = trial_set
    )
  ) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(
    x = "Trial Number",
    y = NULL
  )

# add horizontal lines
p <- p +
  geom_hline(
    yintercept = c(0, 30), linewidth = 0.4,
    colour = "#CCCCCC", linetype = "solid"
  ) +
  geom_hline(
    yintercept = c(15), linewidth = 0.4,
    colour = "#CCCCCC", linetype = "dashed"
  )

# add axis ticks
p <- p +
  scale_y_continuous(
    limits = c(-15, 40),
    breaks = c(0, 15, 30),
    labels = c(0, 15, 30)
  )

# set font size to 11
p <- p +
  theme(text = element_text(size = 11))

# add data points
p <- p +
  geom_beeswarm(
    data = data_ppt,
    aes(y = mean_trial_set_angle),
    alpha = 0.1,
    size = 1
  ) +
  geom_linerange(aes(
    ymin = trial_set_mean - trial_set_ci,
    ymax = trial_set_mean + trial_set_ci
  ), alpha = 0.5, lwd = 2)

p <- p +
  scale_color_manual(
    values = c(
      "#f07c04", "#a30f15"
    )
  )

p <- p +
  scale_x_discrete(
    labels = c(
      "Init", "Fin"
    )
  )

# save
ggsave(
  p,
  filename = "../plots/paper_figs/sr_30_trial_set.pdf", device = "pdf",
  height = 4, width = 2
)

p
```


# S30 Clamped
```{r}
sr_30_ppt_clamped <- sr_30_clamped %>%
  group_by(ppid, trained_obj_hand_factor) %>%
  summarise(
    ppt_mean_unsigned_angle = mean(unsigned_angle),
    ci_unsigned_angle = vector_confint(unsigned_angle)
  ) %>%
  mutate (fixed_angle = case_when(
    (trained_obj_hand_factor == "untrained_obj_trained_hand") |
    (trained_obj_hand_factor == "untrained_obj_untrained_hand") ~ ppt_mean_unsigned_angle * -1,
    TRUE ~ ppt_mean_unsigned_angle
  ))


sr_30_obj_hand_clamped <- sr_30_ppt_clamped %>%
  group_by(trained_obj_hand_factor) %>%
  summarise(
    mean_unsigned_angle = mean(fixed_angle),
    ci_unsigned_angle = vector_confint(fixed_angle)
  ) 
data_ppt <- sr_30_ppt_clamped
data_obj_hand_factor <- sr_30_obj_hand_clamped

# set up plot
p <- data_obj_hand_factor %>%
  ggplot(
    aes(
      x = factor(trained_obj_hand_factor, levels = 
                   c("trained_obj_trained_hand", "untrained_obj_trained_hand", 
                 "trained_obj_untrained_hand", "untrained_obj_untrained_hand")),
      y = mean_unsigned_angle,
      color = trained_obj_hand_factor
    )
  ) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(
    x = "Trial Number",
    y = "Angular Error (°)"
  )

# add horizontal lines
p <- p +
  geom_hline(
    yintercept = c(0, 30), linewidth = 0.4,
    colour = "#CCCCCC", linetype = "solid"
  ) +
  geom_hline(
    yintercept = c(15), linewidth = 0.4,
    colour = "#CCCCCC", linetype = "dashed"
  )

# add axis ticks
# p <- p +
#   scale_y_continuous(
#     limits = c(-15, 40),
#     breaks = c(0, 15, 30),
#     labels = c(0, 15, 30)
#   )

# set font size to 11
p <- p +
  theme(text = element_text(size = 11))

# add data points
p <- p +
  geom_beeswarm(
    data = data_ppt,
    aes(
      x = factor(trained_obj_hand_factor, levels = 
                   c("trained_obj_trained_hand", "untrained_obj_trained_hand", 
                 "trained_obj_untrained_hand", "untrained_obj_untrained_hand")),
      y = fixed_angle),
    alpha = 0.1,
    size = 1
  ) +
  geom_linerange(aes(
    ymin = mean_unsigned_angle - ci_unsigned_angle,
    ymax = mean_unsigned_angle + ci_unsigned_angle
  ), alpha = 0.5, lwd = 2) +
  geom_point()

p <- p +
  scale_color_manual(
    values = c(
      "#f07c04", "#a30f15",
      "#f07c04", "#a30f15"
    )
  )

p <- p +
  scale_x_discrete(
    breaks = c("trained_obj_trained_hand", "untrained_obj_trained_hand", 
               "trained_obj_untrained_hand", "untrained_obj_untrained_hand"),
    labels = c(
      "Trained Shape \nTrained Hand", "Unrained Shape \nTrained Hand",
      "Trained Shape \nUntrained Hand", "Untrained Shape \nUntrained Hand"
    )
  )

# save
ggsave(
  p,
  filename = "../plots/paper_figs/sr_30_clamped.pdf", device = "pdf",
  height = 4, width = 4
)

p
```



```{r}
# empty
```

